services:
  n8n:
    image: n8nio/n8n
    env_file:
      - ./.env
    ports:
      - "${N8N_PORT_EXTERNAL}:${N8N_PORT_INTERNAL}"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - DB_TYPE=${N8N_DB_TYPE}
      - DB_POSTGRESDB_HOST=${N8N_DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${N8N_DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${N8N_DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${N8N_DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${N8N_DB_POSTGRESDB_PASSWORD}
      - NODE_FUNCTION_ALLOW_EXTERNAL=${N8N_NODE_FUNCTION_ALLOW_EXTERNAL}
    depends_on:
      - n8n-db
    restart: no
    networks:
      - n8n-nw

  n8n-db:
    image: postgres:12
    volumes:
      - n8n-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${N8N_DB_POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${N8N_DB_POSTGRESDB_PASSWORD}
      - POSTGRES_DB=${N8N_DB_POSTGRESDB_DATABASE}
    restart: unless-stopped
    networks:
      - n8n-nw

networks:
  n8n-nw:
    driver: "overlay"
    attachable: true

volumes:
  n8n-db-data: