services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID=1000 # -- optional, your user id
      - PGID=1000 # -- optional, your group id
      - LOG_LEVEL=debug
    ports:
      - ${HOMEPAGE_PORT_EXTERNAL}:${HOMEPAGE_PORT_INTERNAL}
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - homepage-data-images:/app/public/images
      - homepage-data-icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped

volumes:
  homepage-data-images:
  homepage-data-icons: