# TuxTechIaaC Funding Options
# Thank you for considering supporting our project!
# Currently, we're focused on building and growing the project.
# Check back soon for sponsorship opportunities and ways to contribute.

# Future funding platforms will be enabled here
# github: [tuxtechlab]
# patreon: yourusername
# open_collective: tuxtechiaac
# ko_fi: yourusername
# buy_me_a_coffee: yourusername

# For now, you can support us by:
# - Starring the repository 
# - Contributing code or documentation
# - Sharing the project with others

# For sponsorship inquiries, please contact us at:
# contact@tuxtechlab.com